/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto.Ventanas;

import java.awt.Color;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import proyecto.Empresa;
import proyecto.Tienda;

/**
 *
 * @author Estudiante_2
 */
public class ventanaMenuArticulos_AñadirEliminarModificarArticulos extends javax.swing.JFrame {

    /**
     * Creates new form ventanaMenuArticulos_AñadirEliminarModificarArticulos
     */
    Empresa best;
    Tienda tienda;
    public ventanaMenuArticulos_AñadirEliminarModificarArticulos(Empresa bestEmpresa,Tienda tienda1) {
        initComponents();
        tienda = tienda1;
        best = bestEmpresa;
        mnA_AEMA_overlay.setBackground(new Color(0,0,0,100));
        DefaultListModel<String> mdl = best.crearMdlVendedores(tienda.getID());
        mnAddGer_jList2.setModel(mdl);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mnA_AEMA_overlay = new javax.swing.JPanel();
        mnArticulos_mnTienda = new javax.swing.JButton();
        pnl_msgID = new javax.swing.JPanel();
        jlabel_nombre = new javax.swing.JLabel();
        mnAddGer_nombre = new javax.swing.JTextField();
        pnl_msgID1 = new javax.swing.JPanel();
        jlabel_rut = new javax.swing.JLabel();
        mnAddGer_rut = new javax.swing.JTextField();
        pnl_msgID2 = new javax.swing.JPanel();
        jlabel_sueldoger = new javax.swing.JLabel();
        mnAddGer_sueldo = new javax.swing.JTextField();
        mnAddGer_jB_modificar = new javax.swing.JButton();
        mnAddGer_jB_Eliminar = new javax.swing.JButton();
        mnAddGer_jList = new javax.swing.JScrollPane();
        mnAddGer_jList2 = new javax.swing.JList<>();
        mnAddGer_jB_agregar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mnA_AEMA_overlay.setBackground(new java.awt.Color(0, 0, 0));
        mnA_AEMA_overlay.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mnArticulos_mnTienda.setText("Volver al menu anterior");
        mnArticulos_mnTienda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnArticulos_mnTiendaActionPerformed(evt);
            }
        });
        mnA_AEMA_overlay.add(mnArticulos_mnTienda, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 490, -1, -1));

        pnl_msgID.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlabel_nombre.setText("Ingresa el nombre del Vendedor");
        pnl_msgID.add(jlabel_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 190, 20));

        mnA_AEMA_overlay.add(pnl_msgID, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 220, 40));
        mnA_AEMA_overlay.add(mnAddGer_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 220, -1));

        pnl_msgID1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlabel_rut.setText("Ingresa el RUT del Vendedor");
        pnl_msgID1.add(jlabel_rut, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 150, 20));

        mnA_AEMA_overlay.add(pnl_msgID1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 220, 40));
        mnA_AEMA_overlay.add(mnAddGer_rut, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 220, -1));

        pnl_msgID2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlabel_sueldoger.setText("Ingresa el sueldo del Vendedor");
        pnl_msgID2.add(jlabel_sueldoger, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 150, 20));

        mnA_AEMA_overlay.add(pnl_msgID2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 220, 40));
        mnA_AEMA_overlay.add(mnAddGer_sueldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, 220, -1));

        mnAddGer_jB_modificar.setText("Modificar Vendedor");
        mnAddGer_jB_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnAddGer_jB_modificarActionPerformed(evt);
            }
        });
        mnA_AEMA_overlay.add(mnAddGer_jB_modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 440, -1, -1));

        mnAddGer_jB_Eliminar.setText("Eliminar Vendedor");
        mnAddGer_jB_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnAddGer_jB_EliminarActionPerformed(evt);
            }
        });
        mnA_AEMA_overlay.add(mnAddGer_jB_Eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 490, -1, -1));

        mnAddGer_jList.setViewportView(mnAddGer_jList2);

        mnA_AEMA_overlay.add(mnAddGer_jList, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, 520, 340));

        mnAddGer_jB_agregar.setText("Agregar Vendedor");
        mnAddGer_jB_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnAddGer_jB_agregarActionPerformed(evt);
            }
        });
        mnA_AEMA_overlay.add(mnAddGer_jB_agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 390, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 880, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(mnA_AEMA_overlay, javax.swing.GroupLayout.PREFERRED_SIZE, 880, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(mnA_AEMA_overlay, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnArticulos_mnTiendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnArticulos_mnTiendaActionPerformed
        ventanaMenuTienda mn = new ventanaMenuTienda(best,tienda);
        mn.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mnArticulos_mnTiendaActionPerformed

    private void mnAddGer_jB_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnAddGer_jB_modificarActionPerformed
        String nombre = mnAddGer_nombre.getText();
        String rut = mnAddGer_rut.getText();
        String sueldo = mnAddGer_sueldo.getText();
        
        if(nombre.isEmpty()||rut.isEmpty()||sueldo.isEmpty()){
            JOptionPane.showMessageDialog(null,"No es posible modificar un Vendedor con algun campo vacio.");
            return;
        }
        String rutnuevo = JOptionPane.showInputDialog("Ingrese el nuevo rut: ");
        if(best.modificarVendedor(nombre, rut, sueldo,rutnuevo,tienda.getID()) == -1){
            JOptionPane.showMessageDialog(null,"No existe un vendedor con ese rut.");
            return;
        }
        
        JOptionPane.showMessageDialog(null,"Vendedor/a modificado Exitosamente.");
    }//GEN-LAST:event_mnAddGer_jB_modificarActionPerformed

    private void mnAddGer_jB_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnAddGer_jB_EliminarActionPerformed
        String rut = mnAddGer_rut.getText();
        if(rut.isEmpty()){
            JOptionPane.showMessageDialog(null,"No es posible eliminar a un vendedor sin el rut.");
            return;
        }
        
        if(best.eliminarVendedor(rut, tienda.getID()) == -1){
            JOptionPane.showMessageDialog(null,"No existe un vendedor con ese rut.");
            return;
        }
        
        JOptionPane.showMessageDialog(null,"Vendedor/a eliminado Exitosamente.");
    }//GEN-LAST:event_mnAddGer_jB_EliminarActionPerformed

    private void mnAddGer_jB_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnAddGer_jB_agregarActionPerformed
        String nombre = mnAddGer_nombre.getText();
        String rut = mnAddGer_rut.getText();
        String sueldo = mnAddGer_sueldo.getText();
        
        if(nombre.isEmpty()||rut.isEmpty()||sueldo.isEmpty()){
            JOptionPane.showMessageDialog(null,"No es posible crear un Vendedor con algun campo vacio.");
            return;
        }
        
        if(best.agregarVendedor(nombre, rut, sueldo,tienda.getID()) == -1){
            JOptionPane.showMessageDialog(null,"Ya esta registrado un vendedor con ese rut.");
            return;
        }
        
        JOptionPane.showMessageDialog(null,"Vendedor/a Agregado Exitosamente.");
    }//GEN-LAST:event_mnAddGer_jB_agregarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jlabel_nombre;
    private javax.swing.JLabel jlabel_rut;
    private javax.swing.JLabel jlabel_sueldoger;
    private javax.swing.JPanel mnA_AEMA_overlay;
    private javax.swing.JButton mnAddGer_jB_Eliminar;
    private javax.swing.JButton mnAddGer_jB_agregar;
    private javax.swing.JButton mnAddGer_jB_modificar;
    private javax.swing.JScrollPane mnAddGer_jList;
    private javax.swing.JList<String> mnAddGer_jList2;
    private javax.swing.JTextField mnAddGer_nombre;
    private javax.swing.JTextField mnAddGer_rut;
    private javax.swing.JTextField mnAddGer_sueldo;
    private javax.swing.JButton mnArticulos_mnTienda;
    private javax.swing.JPanel pnl_msgID;
    private javax.swing.JPanel pnl_msgID1;
    private javax.swing.JPanel pnl_msgID2;
    // End of variables declaration//GEN-END:variables
}
