/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto.Ventanas;

/**
 *
 * @author Estudiante_2
 */
public class ventanaMenuTienda_AñadirEliminarModificarVendedor extends javax.swing.JFrame {

    /**
     * Creates new form ventanaMenuTienda_AñadirEliminarModificarVendedor
     */
    public ventanaMenuTienda_AñadirEliminarModificarVendedor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mnT_AEMV_overlay = new javax.swing.JPanel();
        mnArticulos_AñadirArticulo = new javax.swing.JButton();
        mnArticulos_mnTienda = new javax.swing.JButton();
        mnArticulos_EliminarArticulo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mnT_AEMV_overlay.setBackground(new java.awt.Color(0, 0, 0));
        mnT_AEMV_overlay.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mnArticulos_AñadirArticulo.setText("Añadir/Eliminar/Modificar Articulos");
        mnArticulos_AñadirArticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnArticulos_AñadirArticuloActionPerformed(evt);
            }
        });
        mnT_AEMV_overlay.add(mnArticulos_AñadirArticulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, 200, -1));

        mnArticulos_mnTienda.setText("Volver al menu anterior");
        mnArticulos_mnTienda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnArticulos_mnTiendaActionPerformed(evt);
            }
        });
        mnT_AEMV_overlay.add(mnArticulos_mnTienda, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 490, -1, -1));

        mnArticulos_EliminarArticulo.setText("Exportar Articulos");
        mnArticulos_EliminarArticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnArticulos_EliminarArticuloActionPerformed(evt);
            }
        });
        mnT_AEMV_overlay.add(mnArticulos_EliminarArticulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, 120, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 880, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(mnT_AEMV_overlay, javax.swing.GroupLayout.PREFERRED_SIZE, 880, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(mnT_AEMV_overlay, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnArticulos_AñadirArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnArticulos_AñadirArticuloActionPerformed

    }//GEN-LAST:event_mnArticulos_AñadirArticuloActionPerformed

    private void mnArticulos_mnTiendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnArticulos_mnTiendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnArticulos_mnTiendaActionPerformed

    private void mnArticulos_EliminarArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnArticulos_EliminarArticuloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnArticulos_EliminarArticuloActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventanaMenuTienda_AñadirEliminarModificarVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventanaMenuTienda_AñadirEliminarModificarVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventanaMenuTienda_AñadirEliminarModificarVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventanaMenuTienda_AñadirEliminarModificarVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventanaMenuTienda_AñadirEliminarModificarVendedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton mnArticulos_AñadirArticulo;
    private javax.swing.JButton mnArticulos_EliminarArticulo;
    private javax.swing.JButton mnArticulos_mnTienda;
    private javax.swing.JPanel mnT_AEMV_overlay;
    // End of variables declaration//GEN-END:variables
}
