/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto.Ventanas;

import java.awt.Color;
import javax.swing.JOptionPane;
import proyecto.Empresa;
import proyecto.Tienda;
import proyecto.Vendedor;

/**
 *
 * @author Estudiante_2
 */
public class ventanaMenuTienda extends javax.swing.JFrame {

    /**
     * Creates new form ventanaMenuTienda
     */
    Empresa best;
    Tienda tienda;
    public ventanaMenuTienda(Empresa bestEmpresa, Tienda tienda1) {
        initComponents();
        best = bestEmpresa;
        tienda = tienda1;
        mnTienda_overlay.setBackground(new Color(0,0,0,100));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mnTienda_overlay = new javax.swing.JPanel();
        mnTienda_mnPrincipal = new javax.swing.JButton();
        mnTienda_AddDelEditVendedor = new javax.swing.JButton();
        mnTienda_menuArticulos = new javax.swing.JButton();
        mnTienda_setearCambiarGerente = new javax.swing.JButton();
        mnTienda_menuVendedor = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mnTienda_overlay.setBackground(new java.awt.Color(0, 0, 0));
        mnTienda_overlay.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mnTienda_mnPrincipal.setText("Volver al Menu principal");
        mnTienda_mnPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnTienda_mnPrincipalActionPerformed(evt);
            }
        });
        mnTienda_overlay.add(mnTienda_mnPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 490, -1, -1));

        mnTienda_AddDelEditVendedor.setText("Añadir/Eliminar/Modificar Vendedor");
        mnTienda_AddDelEditVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnTienda_AddDelEditVendedorActionPerformed(evt);
            }
        });
        mnTienda_overlay.add(mnTienda_AddDelEditVendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 340, -1, -1));

        mnTienda_menuArticulos.setText("Menu Articulos");
        mnTienda_menuArticulos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnTienda_menuArticulosActionPerformed(evt);
            }
        });
        mnTienda_overlay.add(mnTienda_menuArticulos, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 220, 120, -1));

        mnTienda_setearCambiarGerente.setText("Cambiar Gerente");
        mnTienda_setearCambiarGerente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnTienda_setearCambiarGerenteActionPerformed(evt);
            }
        });
        mnTienda_overlay.add(mnTienda_setearCambiarGerente, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, 120, -1));

        mnTienda_menuVendedor.setText("Menu Vendedor");
        mnTienda_menuVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnTienda_menuVendedorActionPerformed(evt);
            }
        });
        mnTienda_overlay.add(mnTienda_menuVendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 280, 120, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 880, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(mnTienda_overlay, javax.swing.GroupLayout.PREFERRED_SIZE, 880, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(mnTienda_overlay, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnTienda_mnPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnTienda_mnPrincipalActionPerformed
        ventanaMenuPrincipal mnprn = new ventanaMenuPrincipal(best);
        mnprn.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mnTienda_mnPrincipalActionPerformed

    private void mnTienda_AddDelEditVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnTienda_AddDelEditVendedorActionPerformed
           ventanaMenuTienda_AñadirEliminarModificarVendedores mn 
           = new ventanaMenuTienda_AñadirEliminarModificarVendedores(best,tienda);
           mn.setVisible(true);
           this.dispose();
        
    }//GEN-LAST:event_mnTienda_AddDelEditVendedorActionPerformed

    private void mnTienda_menuArticulosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnTienda_menuArticulosActionPerformed
        ventanaMenuArticulos mn = new ventanaMenuArticulos(best,tienda);
        mn.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mnTienda_menuArticulosActionPerformed

    private void mnTienda_setearCambiarGerenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnTienda_setearCambiarGerenteActionPerformed
        ventanaMenuTienda_CambiarGerente mn = new ventanaMenuTienda_CambiarGerente(best,tienda);
        mn.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mnTienda_setearCambiarGerenteActionPerformed

    private void mnTienda_menuVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnTienda_menuVendedorActionPerformed
        String rut = JOptionPane.showInputDialog("Ingrese el rut del vendedor: ");
        Vendedor aux = tienda.buscarVendedor(rut);
        if(aux == null){
            JOptionPane.showMessageDialog(null,"No existe vendedor con tal rut.");
            return;
        }
        
        ventanaMenuVendedor mn = new ventanaMenuVendedor(best,tienda,aux);
        mn.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mnTienda_menuVendedorActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton mnTienda_AddDelEditVendedor;
    private javax.swing.JButton mnTienda_menuArticulos;
    private javax.swing.JButton mnTienda_menuVendedor;
    private javax.swing.JButton mnTienda_mnPrincipal;
    private javax.swing.JPanel mnTienda_overlay;
    private javax.swing.JButton mnTienda_setearCambiarGerente;
    // End of variables declaration//GEN-END:variables
}
