package proyecto.Ventanas;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Zekro
 */
import java.awt.*;
import javax.swing.JOptionPane;
import proyecto.Empresa;
public class ventanaLogin extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    Empresa best;
    public ventanaLogin(Empresa bestEmpresa) {
        initComponents();
        pnl_overlay.setBackground(new Color(0,0,0,100));
        pnl_overlay2.setBackground(new Color(0,0,0,100));
        best = bestEmpresa;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_overlay2 = new javax.swing.JPanel();
        pnlIcon_login = new javax.swing.JLabel();
        pnlIcon_loginarrow = new javax.swing.JLabel();
        pnlIcon_password = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtPassword = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        txtUserLogin = new javax.swing.JTextField();
        pnl_enterbutton = new javax.swing.JButton();
        pnl_overlay = new javax.swing.JPanel();
        pnlIcon_logo = new javax.swing.JLabel();
        pnlTxt_slogan = new javax.swing.JLabel();
        pnl_bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Easy Shop Login");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnl_overlay2.setBackground(new java.awt.Color(0, 0, 0));
        pnl_overlay2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlIcon_login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pnl_login.png"))); // NOI18N
        pnl_overlay2.add(pnlIcon_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, -30, -1, -1));

        pnlIcon_loginarrow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pnl_login2.png"))); // NOI18N
        pnl_overlay2.add(pnlIcon_loginarrow, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        pnlIcon_password.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pnl_Password.png"))); // NOI18N
        pnl_overlay2.add(pnlIcon_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(153, 153, 153));
        pnl_overlay2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 150, 10));

        txtPassword.setBackground(new java.awt.Color(0, 0, 0));
        txtPassword.setForeground(new java.awt.Color(255, 255, 255));
        txtPassword.setToolTipText("");
        txtPassword.setBorder(null);
        pnl_overlay2.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 150, 20));

        jSeparator2.setBackground(new java.awt.Color(153, 153, 153));
        pnl_overlay2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 150, 10));

        txtUserLogin.setBackground(new java.awt.Color(0, 0, 0));
        txtUserLogin.setForeground(new java.awt.Color(255, 255, 255));
        txtUserLogin.setBorder(null);
        pnl_overlay2.add(txtUserLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 150, 20));

        pnl_enterbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pnl_enterlogin.png"))); // NOI18N
        pnl_enterbutton.setContentAreaFilled(false);
        pnl_enterbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnl_enterbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pnl_enterbuttonActionPerformed(evt);
            }
        });
        pnl_overlay2.add(pnl_enterbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 289, 60, 60));

        getContentPane().add(pnl_overlay2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 120, 320, 360));

        pnl_overlay.setBackground(new java.awt.Color(0, 0, 0));
        pnl_overlay.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlIcon_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pnl_logo.png"))); // NOI18N
        pnl_overlay.add(pnlIcon_logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, -1, -1));

        pnlTxt_slogan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pnl_slogan.png"))); // NOI18N
        pnlTxt_slogan.setPreferredSize(new java.awt.Dimension(370, 50));
        pnl_overlay.add(pnlTxt_slogan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 360, -1));

        getContentPane().add(pnl_overlay, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 610));

        pnl_bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pnl_bg.png"))); // NOI18N
        pnl_bg.setText("x");
        getContentPane().add(pnl_bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(-590, 0, 1470, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pnl_enterbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pnl_enterbuttonActionPerformed
        String user = txtUserLogin.getText();
        String password = txtPassword.getText();
        if(user.isEmpty() || password.isEmpty()){
            JOptionPane.showMessageDialog(null, "Hay algun campo vacio");
        }else if(user.equals("root") && password.equals("123456")){
            JOptionPane.showMessageDialog(null,"Bienvenido");
            this.dispose();
            ventanaMenuPrincipal menu = new ventanaMenuPrincipal(best);
            menu.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(null, "Contraseña o Usuario incorrectos");
        }
    }//GEN-LAST:event_pnl_enterbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel pnlIcon_login;
    private javax.swing.JLabel pnlIcon_loginarrow;
    private javax.swing.JLabel pnlIcon_logo;
    private javax.swing.JLabel pnlIcon_password;
    private javax.swing.JLabel pnlTxt_slogan;
    private javax.swing.JLabel pnl_bg;
    private javax.swing.JButton pnl_enterbutton;
    private javax.swing.JPanel pnl_overlay;
    private javax.swing.JPanel pnl_overlay2;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUserLogin;
    // End of variables declaration//GEN-END:variables
}
