/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto.Ventanas;

import java.awt.Color;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import proyecto.Articulo;
import proyecto.Empresa;
import proyecto.Tienda;
import proyecto.Vendedor;

/**
 *
 * @author Zekro
 */
public class ventanaMenuVendedor_AñadirVerFacturas extends javax.swing.JFrame {

    /**
     * Creates new form ventanaMenuVendedor_AñadirVerFacturas
     */
    private Empresa best;
    private Tienda tienda;
    private Vendedor vend;
    public ventanaMenuVendedor_AñadirVerFacturas(Empresa bestEmpresa,Tienda tienda1,Vendedor vn1) {
        initComponents();
        best=bestEmpresa;
        tienda=tienda1;
        vend = vn1;
        mnVendedor_overlay.setBackground(new Color(0,0,0,100));
        DefaultListModel<String> mdl = vend.mdlFacturas();
        mnAddGer_jList2.setModel(mdl);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mnVendedor_overlay = new javax.swing.JPanel();
        mnVendedor_mnTienda = new javax.swing.JButton();
        mnVendedor_ExportarFacturas = new javax.swing.JButton();
        mnAddGer_jList = new javax.swing.JScrollPane();
        mnAddGer_jList2 = new javax.swing.JList<>();
        mnAddGer_nombre = new javax.swing.JTextField();
        pnl_msgID = new javax.swing.JPanel();
        jlabel_nombre = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mnVendedor_overlay.setBackground(new java.awt.Color(0, 0, 0));
        mnVendedor_overlay.setPreferredSize(new java.awt.Dimension(880, 610));
        mnVendedor_overlay.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mnVendedor_mnTienda.setText("Volver al menu anterior");
        mnVendedor_mnTienda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnVendedor_mnTiendaActionPerformed(evt);
            }
        });
        mnVendedor_overlay.add(mnVendedor_mnTienda, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 490, -1, -1));

        mnVendedor_ExportarFacturas.setText("Crear Factura");
        mnVendedor_ExportarFacturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnVendedor_ExportarFacturasActionPerformed(evt);
            }
        });
        mnVendedor_overlay.add(mnVendedor_ExportarFacturas, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 490, -1, -1));

        mnAddGer_jList.setViewportView(mnAddGer_jList2);

        mnVendedor_overlay.add(mnAddGer_jList, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, 520, 340));
        mnVendedor_overlay.add(mnAddGer_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 220, -1));

        pnl_msgID.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlabel_nombre.setText("Ingresa la ID de la factura");
        pnl_msgID.add(jlabel_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 190, 20));

        mnVendedor_overlay.add(pnl_msgID, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 220, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 880, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(mnVendedor_overlay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(mnVendedor_overlay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnVendedor_mnTiendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnVendedor_mnTiendaActionPerformed
        ventanaMenuTienda mn = new ventanaMenuTienda(best,tienda);
        mn.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mnVendedor_mnTiendaActionPerformed

    private void mnVendedor_ExportarFacturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnVendedor_ExportarFacturasActionPerformed
        String id = mnAddGer_nombre.getText();
        if(vend.buscarSiExisteFactura(id)==-1){
            JOptionPane.showMessageDialog(null,"Ya existe una factura ligada a tal ID.");
            return;
        }
        String codigo = JOptionPane.showInputDialog("Ingrese la id del Articulo: ");
        Articulo aux = tienda.buscarArticulo(codigo);
        if(aux == null){
            JOptionPane.showMessageDialog(null,"No existe ese articulo.");
            return;
        }
            
        vend.añadirFactura(vend.getRut(), id, aux);
        int option;
        if (JOptionPane.showConfirmDialog(null, "¿Estas seguro?", "Cuidado",
            JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION)option = 1;
        else option = 0;
         
        while(option != 0){
            
            String codigo2 = JOptionPane.showInputDialog("Ingrese la id del Articulo: ");
            Articulo aux2 = tienda.buscarArticulo(codigo2);
            if(aux2 == null){
                JOptionPane.showMessageDialog(null,"No existe ese articulo.");
                continue;
            }
            vend.añadirArticuloFactura(id, aux2);
            
            
            if (JOptionPane.showConfirmDialog(null, "¿Estas seguro?", "Cuidado",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION)option = 1;
            else option = 0;
        }
    }//GEN-LAST:event_mnVendedor_ExportarFacturasActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jlabel_nombre;
    private javax.swing.JScrollPane mnAddGer_jList;
    private javax.swing.JList<String> mnAddGer_jList2;
    private javax.swing.JTextField mnAddGer_nombre;
    private javax.swing.JButton mnVendedor_ExportarFacturas;
    private javax.swing.JButton mnVendedor_mnTienda;
    private javax.swing.JPanel mnVendedor_overlay;
    private javax.swing.JPanel pnl_msgID;
    // End of variables declaration//GEN-END:variables
}
