/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto.Ventanas;

import proyecto.Ventanas.ventanaMostrarTiendas;
import java.awt.Color;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import javax.swing.JOptionPane;
import proyecto.Empresa;

/**
 *
 * @author Zekro
 */
public class ventanaMenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form ventanaMenuPrincipal
     * @throws java.lang.InterruptedException
     * @throws java.io.IOException
     */
    Empresa best;
    public ventanaMenuPrincipal(Empresa bestEmpresa) {
        initComponents();
        mn_overlay.setBackground(new Color(0,0,0,100));
        best = bestEmpresa;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mn_overlay = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        mn_jB_cerrarsesion = new javax.swing.JButton();
        mn_jB_eliminarTienda = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        mn_bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Easy Shop");
        setMinimumSize(new java.awt.Dimension(880, 610));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mn_overlay.setBackground(new java.awt.Color(0, 0, 0));
        mn_overlay.setPreferredSize(new java.awt.Dimension(880, 610));
        mn_overlay.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Menu Tienda");
        mn_overlay.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 110, -1));

        mn_jB_cerrarsesion.setText("Salir");
        mn_jB_cerrarsesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_jB_cerrarsesionActionPerformed(evt);
            }
        });
        mn_overlay.add(mn_jB_cerrarsesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 470, 100, -1));

        mn_jB_eliminarTienda.setText("Eliminar Tienda");
        mn_jB_eliminarTienda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_jB_eliminarTiendaActionPerformed(evt);
            }
        });
        mn_overlay.add(mn_jB_eliminarTienda, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 110, -1));

        jButton3.setText("Agregar Tienda");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        mn_overlay.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 110, -1));

        jButton2.setText("Ver Tiendas");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        mn_overlay.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 110, -1));

        getContentPane().add(mn_overlay, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 610));

        mn_bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mn_bg.jpg"))); // NOI18N
        mn_bg.setMaximumSize(new java.awt.Dimension(880, 610));
        mn_bg.setMinimumSize(new java.awt.Dimension(880, 610));
        mn_bg.setPreferredSize(new java.awt.Dimension(880, 610));
        getContentPane().add(mn_bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mn_jB_cerrarsesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_jB_cerrarsesionActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mn_jB_cerrarsesionActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        ventanaAgregarTienda ventanaAgregar = new ventanaAgregarTienda(best);
        ventanaAgregar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void mn_jB_eliminarTiendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_jB_eliminarTiendaActionPerformed
        ventanaEliminarTienda ventanaEliminar = new ventanaEliminarTienda(best);
        ventanaEliminar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mn_jB_eliminarTiendaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        ventanaMostrarTiendas showShop = new ventanaMostrarTiendas(best);
        showShop.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     * @throws java.io.IOException
     * @throws java.lang.InterruptedException
     */
   /* public static void main(String args[]) throws IOException, InterruptedException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        
        //</editor-fold>

        /* Create and display the form */
       /* java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventanaMenuPrincipal().setVisible(true);
                        
            }
        });
    }*/
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel mn_bg;
    private javax.swing.JButton mn_jB_cerrarsesion;
    private javax.swing.JButton mn_jB_eliminarTienda;
    private javax.swing.JPanel mn_overlay;
    // End of variables declaration//GEN-END:variables

    
}
