/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto.Ventanas;

import java.awt.Color;
import proyecto.Empresa;

/**
 *
 * @author Estudiante_2
 */
public class ventanaMenuArticulos extends javax.swing.JFrame {

    /**
     * Creates new form ventanaMenuArticulos
     */
    Empresa best;
    public ventanaMenuArticulos(Empresa bestEmpresa) {
        initComponents();
        best = bestEmpresa;
        mnArticulos_overlay.setBackground(new Color(0,0,0,100));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mnArticulos_overlay = new javax.swing.JPanel();
        mnArticulos_AñadirArticulo = new javax.swing.JButton();
        mnArticulos_mnTienda = new javax.swing.JButton();
        mnArticulos_EliminarArticulo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mnArticulos_overlay.setBackground(new java.awt.Color(0, 0, 0));
        mnArticulos_overlay.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mnArticulos_AñadirArticulo.setText("Añadir/Eliminar/Modificar Articulos");
        mnArticulos_AñadirArticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnArticulos_AñadirArticuloActionPerformed(evt);
            }
        });
        mnArticulos_overlay.add(mnArticulos_AñadirArticulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, 200, -1));

        mnArticulos_mnTienda.setText("Volver al menu anterior");
        mnArticulos_mnTienda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnArticulos_mnTiendaActionPerformed(evt);
            }
        });
        mnArticulos_overlay.add(mnArticulos_mnTienda, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 490, -1, -1));

        mnArticulos_EliminarArticulo.setText("Exportar Articulos");
        mnArticulos_EliminarArticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnArticulos_EliminarArticuloActionPerformed(evt);
            }
        });
        mnArticulos_overlay.add(mnArticulos_EliminarArticulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, 120, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 880, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(mnArticulos_overlay, javax.swing.GroupLayout.PREFERRED_SIZE, 880, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(mnArticulos_overlay, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnArticulos_AñadirArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnArticulos_AñadirArticuloActionPerformed

    }//GEN-LAST:event_mnArticulos_AñadirArticuloActionPerformed

    private void mnArticulos_mnTiendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnArticulos_mnTiendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnArticulos_mnTiendaActionPerformed

    private void mnArticulos_EliminarArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnArticulos_EliminarArticuloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnArticulos_EliminarArticuloActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton mnArticulos_AñadirArticulo;
    private javax.swing.JButton mnArticulos_EliminarArticulo;
    private javax.swing.JButton mnArticulos_mnTienda;
    private javax.swing.JPanel mnArticulos_overlay;
    // End of variables declaration//GEN-END:variables
}
